---
name: automerge
on:
  pull_request:
    branches:
      - 'master'
    types:
      - labeled
      - unlabeled
  pull_request_review:
    types:
      - submitted
jobs:
  automerge:
    runs-on: ubuntu-20.04
    steps:
      - name: merge labeled PR
        uses: pascalgn/automerge-action@8b306ad1983d0ea68c43e27101123e891ecff104
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "automerge, !wip"
          MERGE_REMOVE_LABELS: "automerge"
          MERGE_COMMIT_MESSAGE: "pull-request-title-and-description"
          MERGE_RETRIES: 3
          MERGE_RETRY_SLEEP: 5000
          MERGE_METHOD: squash
