---
name: Commitlint
on:
  - pull_request
jobs:
  commitlint:
    name: Checking commit message compliance
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          fetch-depth: 0
      - run: echo "module.exports = {plugins:['commitlint-plugin-jira-rules'],extends:['jira'],rules:{'jira-task-id-max-length':[2,'always',15],'header-max-length':[2,'always',120]}};" > commitlint.config.js
      - uses: wagoid/commitlint-github-action@ca212b3558faa549515a96944595cad58a40e047
